### ISSUE TITLE
Android crashing!

### ISSUE THREAD

**Issue by td-gamer-alt** [blueblock6/TransparentCheckpoints#2]
On android if you use this mod even with out any other mod it Automatically crash's
**please** fix your mod _(i hope you fix it)_
**here is a vid of me trying the mod and crashing..**

https://github.com/user-attachments/assets/6ec2d506-9ec9-4ecc-8d78-14a7ea6d15d5

**Comment by blueblock6** [comment]
I won't be home for a few hours but I'll fix it as soon as I can - could you send the crash log?
